# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')


def build(bld):
    module = bld.create_ns3_module('pvpie', ['core', 'traffic-control'])
    module.source = [
        'model/pv-pie-queue-disc.cc',
        'model/double-pie-queue-disc.cc',
        'helper/pvpie-helper.cc',
        'model/packet-marker-queue-disc.cc',
        'model/token-bucket.cc',
        'model/packet-value-tag.cc',
        'model/ecdf.cc',
    ]

    module_test = bld.create_ns3_module_test_library('pvpie')
    module_test.source = [
        'test/pvpie-test-suite.cc',
    ]

    headers = bld(features='ns3header')
    headers.module = 'pvpie'
    headers.source = [
        'model/pv-pie-queue-disc.h',
        'model/double-pie-queue-disc.h',
        'helper/pvpie-helper.h',
        'model/packet-marker-queue-disc.h',
        'model/token-bucket.h',
        'model/packet-value-tag.h',
        'model/ecdf.h',
    ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()
