# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-


def build(bld):
    module = bld.create_ns3_module('pvpie', ['core', 'traffic-control'])
    module.source = [
        'model/ecdf.cc',
        'model/pvpie-queue-disc.cc',
        'model/tl-pvpie-queue-disc.cc',
        'model/packet-marker-queue-disc.cc',
        'model/packet-value-tag.cc',
        'helper/IApplicationHelperFactory.cc',
        'helper/leaf-configuration-helper.cc',
        'helper/aqm-topology-helper.cc'
    ]

    module_test = bld.create_ns3_module_test_library('pvpie')
    module_test.source = [
        'test/pvpie-test-suite.cc',
    ]

    headers = bld(features='ns3header')
    headers.module = 'pvpie'
    headers.source = [
        'model/ecdf.h',
        'model/pvpie-queue-disc.h',
        'model/tl-pvpie-queue-disc.h',
        'model/packet-marker-queue-disc.h',
        'model/packet-value-tag.h',
        'helper/IApplicationHelper.h',
        'helper/IApplicationHelperFactory.h',
        'helper/leaf-configuration-helper.h',
        'helper/aqm-topology-helper.h',
    ]

    # if (bld.env['ENABLE_EXAMPLES']):
    #     bld.recurse('examples')

    bld.ns3_python_bindings()
